controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController


diff_drive_controller:
  ros__parameters:

    left_wheel_names: ["left_wheel_hinge"]
    right_wheel_names: ["right_wheel_hinge"]

    wheel_separation: 0.26
    wheel_radius: 0.10

    publish_rate: 50.0

    odom_frame_id: odom
    base_frame_id: chassis

    position_feedback: true
    open_loop: false

    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    
    use_stamped_vel: false
